//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingDownConsole.App {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinOnlineVoltage {
            get {
                return ((double)(this["MinOnlineVoltage"]));
            }
            set {
                this["MinOnlineVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxOnlineVoltage {
            get {
                return ((double)(this["MaxOnlineVoltage"]));
            }
            set {
                this["MaxOnlineVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double MinConnectedVoltage {
            get {
                return ((double)(this["MinConnectedVoltage"]));
            }
            set {
                this["MinConnectedVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.9")]
        public double MaxConnectedVoltage {
            get {
                return ((double)(this["MaxConnectedVoltage"]));
            }
            set {
                this["MaxConnectedVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinOnHookVoltage {
            get {
                return ((double)(this["MinOnHookVoltage"]));
            }
            set {
                this["MinOnHookVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double MaxOnHookVoltage {
            get {
                return ((double)(this["MaxOnHookVoltage"]));
            }
            set {
                this["MaxOnHookVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double MinOffHookVoltage {
            get {
                return ((double)(this["MinOffHookVoltage"]));
            }
            set {
                this["MinOffHookVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.3")]
        public double MaxOffHookVoltage {
            get {
                return ((double)(this["MaxOffHookVoltage"]));
            }
            set {
                this["MaxOffHookVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MinNoDialToneVoltage {
            get {
                return ((double)(this["MinNoDialToneVoltage"]));
            }
            set {
                this["MinNoDialToneVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MaxNoDialToneVoltage {
            get {
                return ((double)(this["MaxNoDialToneVoltage"]));
            }
            set {
                this["MaxNoDialToneVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int IntervalSeconds {
            get {
                return ((int)(this["IntervalSeconds"]));
            }
            set {
                this["IntervalSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PromptForName {
            get {
                return ((bool)(this["PromptForName"]));
            }
            set {
                this["PromptForName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ringdownuat.flychicago.com:3456")]
        public string WebApiConnectionString {
            get {
                return ((string)(this["WebApiConnectionString"]));
            }
            set {
                this["WebApiConnectionString"] = value;
            }
        }
    }
}
